package chatter.db

import app.cash.sqldelight.db.QueryResult
import app.cash.sqldelight.db.SqlDriver
import app.cash.sqldelight.db.SqlSchema
import chatter.lib.log.getValue
import co.touchlab.kermit.Logger

// perform the migrations for the db
//
// the migrations themselves are generated by `sqldelight` out
// of all written migration files. the `MigrationServices` just
// creates a meta information table that holds the current version
// of the schema. if it is not the same as in the generated migrations
// `sqldelight` will perform a migration
class MigrationService(
    private val schema: SqlSchema<QueryResult.Value<Unit>>,
    private val driver: SqlDriver
) {
    private val logger by Logger

    suspend fun migrate() {
        createVersionTable()

        val oldVersion = prepareMigrationTable()
        val newVersion = schema.version

        if (oldVersion != newVersion) {
            logger.i { "Migrating from $oldVersion to $newVersion" }
            schema.migrate(driver, oldVersion, newVersion)
        }

        setVersion(newVersion)
    }

    private suspend fun setVersion(version: Long) {
        val query = """
            | UPDATE VersionEntity
            | SET version = ?
            | WHERE id = 1
            """.trimMargin()

        withDb {
            driver.execute(null, query, 1) {
                bindLong(0, version)
            }
        }
    }

    private suspend fun prepareMigrationTable(): Long {
        val insertQuery = """
            | INSERT INTO VersionEntity(id, version)
            | VALUES(1, 0)
            | ON CONFLICT (id) DO NOTHING
            """.trimMargin()

        withDb { driver.execute(null, insertQuery, 0) }

        val getVersionQuery = "SELECT version FROM VersionEntity WHERE id = 1"

        val version = withDb {
            driver.executeQuery(null, getVersionQuery, {
                it.next()
                QueryResult.Value(it.getLong(0)!!)
            }, 0).value
        }

        return version
    }

    private suspend fun createVersionTable() {
        val query = """
            |CREATE TABLE IF NOT EXISTS VersionEntity(
            |  id SMALLINT PRIMARY KEY DEFAULT 1,
            |
            |  version SMALLINT NOT NULL
            |)
            """.trimMargin()

        withDb { driver.execute(null, query, 0) }
    }
}
