server {
 listen ${NGINX_PORT};

  location / {
   root /usr/share/nginx/html;

   try_files $uri $uri/ /index.html;
  }

  location /api/ {
    rewrite /api/(.*) /$1  break;
    proxy_pass http://${BACKEND_ADDR}/;
  }

  # Websockets have to explicity be set
  location /api/ws {
    rewrite /api/(.*) /$1  break;
    proxy_pass http://${BACKEND_ADDR}/;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
  }
}
